server:
  port: 8095

spring:
  application:
      name: dc_consumer

eureka:
  instance:
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

dubbo:
  application:
    name: dc_consumer
  registry:
    address: zookeeper://59.110.232.17:2181
  protocol:
    name: dubbo
    port: 20880